WIP: Fixes for macOS
katrinafyi/pac-nix pull request #18
Opened 2024-10-02 21:58 UTC by ncough

Partial fixes for getting builds to work on macOS. Many fixes are quite hacky, hopefully someone who knows what they are doing can fix them properly.

* Explicitly link abseil into `gtirb`, as a dependency of protobuf. Not clear why this isn't done automatically.
* Missing `#include <map>` in `gtirb-pprinter`.
* Disable concurrent souffle builds.
* Explicitly provide an implementation of `protoc` to `basil`, due to issues downloading and caching it.
* Fix a linking issue with `ocamlPackages.z3`.

2024-10-02 22:07 UTC, katrinafyi commented
This is excellent! Thanks for your work. I hope Nix wasn't too frustrating :)

2024-10-02 23:30 UTC, ncough commented
Nix has been mostly pain free. A bit confused on by `basil` build if you get a moment, it passes on my machine but fails on ci. Seems the ci doesn't run the `preConfigure` step.

2024-10-03 01:22 UTC, katrinafyi commented
Basil build is fixed on my computer by https://github.com/katrinafyi/pac-nix/pull/18/commits/302dd59b05957c8904d2123a8ec9b9ddb2bcb945. This happened because the configure phase was not being run in the _dependency_ derivation, which mkSbtDerivation runs to download all dependencies (evidenced by the `basil-sbt-dependencies.tar.zst>` prefix in front of the log messages, instead of `basil>`). Within this derivation, configuring [is explicitly disabled](https://github.com/zaninime/sbt-derivation/blob/6762cf2c31de50efd9ff905cbcc87239995a4ef9/lib/dependencies.nix#L42).

Propagating the replacement command makes it work. I suspect some caching was at play to make it succeed locally.

2024-10-03 01:45 UTC, katrinafyi commented
Re protobuf abseil linking errors: https://www.github.com/protocolbuffers/protobuf/issues/12637

2024-10-08 10:28 UTC, ncough commented
From what I see locally, the only remaining issue is the determinism fix for ddisasm not working on macOS. If this isn't used, I suspect it would be far easier to disable the test.

2024-10-09 00:01 UTC, katrinafyi commented
It looks really good now! Just one thing left, we should make the ddisasm test use a "nolibc" variant of the compiler so it doesn't spin cross-compiling libc. I can look into this if you want.

2024-10-09 00:10 UTC, ncough commented
Thanks! I'll leave it to you. I was wondering if it would be possible to have Nix provide a full cross compiling environment on macOS anyway, as full tests aren't practical without it.

2024-10-09 02:34 UTC, katrinafyi requested changes
todo notes for myself

2024-10-09 02:34 UTC, katrinafyi commented on aslp/aslp-cpp.nix
> +let buildStdenv = if stdenv.isDarwin then overrideCC stdenv llvmPackages_17.clang else stdenv; in
investigate better way. i assume this is just to obtain std::format

2024-10-09 02:34 UTC, katrinafyi commented on bap/bap.nix
> +    wrapProgram $out/bin/bap --prefix DYLD_FALLBACK_LIBRARY_PATH : ${z3.lib}/lib
simply move into bap package

2024-10-09 02:34 UTC, katrinafyi commented on basil/0001-basil-protoc-version.patch
> ++PB.protocExecutable := file("PROTOC_PLACEHOLDER")
investigate possibility of upstreaming through a more flexible method

2024-10-09 02:34 UTC, katrinafyi commented on gtirb/ddisasm.nix
> +  patches = if stdenv.isDarwin then [ ./0001-ddisasm-disable-concurrent-souffle.patch ] else [];
use null to avoid rebuild on x86

2024-10-09 02:34 UTC, katrinafyi commented on gtirb/ddisasm.nix
> +      aarch64-unknown-linux-gnu-cc a.c
investigate nolibc or pre-built binary

2024-10-09 02:34 UTC, katrinafyi commented on llvm-translator/alive2-regehr.nix
> +  CXXFLAGS = prev.CXXFLAGS or "" + (if stdenv.isDarwin then "" else " -Wno-error=maybe-uninitialized");
use lib.optional

2024-10-09 02:34 UTC, katrinafyi commented on overlay.nix
> +        # ctypes and ctypes-foreign v0.22.0 do not build on macOS
investigate...? if possible

2024-10-09 02:34 UTC, katrinafyi commented on .github/workflows/main.yml
>            planter,
remove planter from test list

2024-10-09 16:24 UTC, katrinafyi commented
@ncough real quick about using Nix as a cross-compile  environment, this is definitely possible. but the main problem is the Nix-provided compilers are not hermetic - they will look for and may or may not find libraries on your system. It is especially dicey if the Nix compilers call a non-Nix tool which it finds through PATH.

The solutions I can conceptualise are:
-  run all compilations within a Nix sandbox - clunky, slow, difficult to integrate, adds Nix as a runtime dependency, and bloats Nix store on disk with compilation results
- use Nix compiler within a chroot / Docker - probably easiest. some trouble transporting files across the boundary 
- somehow manually isolate the Nix compiler, e.g. by clearing PATH in a wrapper script - hard

2024-10-30 05:49 UTC, katrinafyi commented on gtirb/ddisasm.nix
> +      aarch64-unknown-linux-gnu-cc a.c
abandoned

2024-10-31 06:35 UTC, katrinafyi approved these changes

2024-12-03 04:14 UTC, merged